### ISSUE TITLE
Change heroku domain name to something Hydra-Connect-ish

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/sessionizer#3]
Current: https://stark-waters-7145.herokuapp.com/home
Desired: something like http://hc2015.herokuapp.com/home or http://hc2015-session.curationexperts.com

**Comment by acozine** [comment]
Updated to http://connect2015.curationexperts.com.
To change:

```
heroku domains:add desiredname.curationexperts.com
```

Then add a CNAME record pointing desiredname to stark-waters-7145.herokuapp.com.
